[package]
name = "assert4rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
num = "0.4.1"
regex = "1.10.2"

[dev-dependencies]
tempdir = "0.3.7"
